// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    // Test name: test2
    // Step # | name | target | value
    // 1 | open | http://127.0.0.1:8080/quiz.html?difficulty=2 | 
    driver.get("http://127.0.0.1:8080/quiz.html?difficulty=2");
    // 2 | click | id=student-code | 
    driver.findElement(By.id("student-code")).click();
    // 3 | click | id=student-code | 
    driver.findElement(By.id("student-code")).click();
    // 4 | type | id=student-code | sdinaka1
    driver.findElement(By.id("student-code")).sendKeys("sdinaka1");
    // 5 | mouseDownAt | css=.container | 121.6328125,110
    {
      WebElement element = driver.findElement(By.cssSelector(".container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 6 | mouseMoveAt | css=.container | 121.6328125,110
    {
      WebElement element = driver.findElement(By.cssSelector(".container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseUpAt | css=.container | 121.6328125,110
    {
      WebElement element = driver.findElement(By.cssSelector(".container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 8 | click | css=.container | 
    driver.findElement(By.cssSelector(".container")).click();
    // 9 | click | css=h1 | 
    driver.findElement(By.cssSelector("h1")).click();
    // 10 | click | css=.container | 
    driver.findElement(By.cssSelector(".container")).click();
    // 11 | click | id=red | 
    driver.findElement(By.id("red")).click();
    // 12 | click | id=green | 
    driver.findElement(By.id("green")).click();
    // 13 | click | id=blue | 
    driver.findElement(By.id("blue")).click();
    // 14 | click | id=red | 
    driver.findElement(By.id("red")).click();
    // 15 | click | css=p:nth-child(10) | 
    driver.findElement(By.cssSelector("p:nth-child(10)")).click();
    // 16 | click | id=quiz-form | 
    driver.findElement(By.id("quiz-form")).click();
    // 17 | click | id=answer-confirm | 
    driver.findElement(By.id("answer-confirm")).click();
    // 18 | click | css=button | 
    driver.findElement(By.cssSelector("button")).click();
  }
}
