// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: test1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://127.0.0.1:8080/result.html?answer=red/");
    // 2 | setWindowSize | 1440x900 | 
    driver.manage().window().setSize(new Dimension(1440, 900));
    // 3 | click | id=student-code | 
    driver.findElement(By.id("student-code")).click();
    // 4 | type | id=student-code | sdinaka1
    driver.findElement(By.id("student-code")).sendKeys("sdinaka1");
    // 5 | click | css=h1 | 
    driver.findElement(By.cssSelector("h1")).click();
    // 6 | click | css=#start-form > label:nth-child(1) | 
    driver.findElement(By.cssSelector("#start-form > label:nth-child(1)")).click();
    // 7 | mouseDownAt | id=difficulty | 179.671875,3.6796875
    {
      WebElement element = driver.findElement(By.id("difficulty"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 8 | mouseMoveAt | id=difficulty | 179.671875,3.6796875
    {
      WebElement element = driver.findElement(By.id("difficulty"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | mouseUpAt | id=difficulty | 179.671875,3.6796875
    {
      WebElement element = driver.findElement(By.id("difficulty"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 10 | type | id=difficulty | 3
    driver.findElement(By.id("difficulty")).sendKeys("3");
    // 11 | click | id=difficulty | 
    driver.findElement(By.id("difficulty")).click();
    // 12 | click | id=confirm-start | 
    driver.findElement(By.id("confirm-start")).click();
    // 13 | click | css=label:nth-child(5) | 
    driver.findElement(By.cssSelector("label:nth-child(5)")).click();
    // 14 | click | css=button | 
    driver.findElement(By.cssSelector("button")).click();
  }
}
